#!/usr/bin/env node
/**
 * Generates src/version.ts with the version baked in from package.json.
 * This runs before TypeScript compilation so the version is a compile-time constant.
 */

const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionTsPath = path.join(__dirname, '..', 'src', 'version.ts');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

const content = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-version.js

export const VERSION = '${packageJson.version}';
export const EXTENSION_NAME = '${packageJson.name}';
export const DISPLAY_NAME = '${packageJson.displayName}';
export const PUBLISHER = '${packageJson.publisher}';
export const EXTENSION_ID = '${packageJson.publisher}.${packageJson.name}';
`;

fs.writeFileSync(versionTsPath, content, 'utf-8');
console.log(`Generated ${versionTsPath} with version ${packageJson.version}`);
