// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-version.js

export const VERSION = '5.1.0';
export const EXTENSION_NAME = 'copilot-script-runner';
export const DISPLAY_NAME = 'Copilot Script Runner';
export const PUBLISHER = 'bdayadev';
export const EXTENSION_ID = 'bdayadev.copilot-script-runner';
